apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative-deployment
  labels:
    app: creative
  namespace: tia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creative
  template:
    metadata:
      labels:
        app: creative
    spec:
      containers:
        - name: creative
          image: leonardtia/tia:creative
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: creative-nodeport-service
  labels:
    app: creative
  namespace: tia
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
spec:
  type: NodePort
  selector:
    app: creative
  ports:
    - port: 80
      targetPort: 80

   