---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-deployment
  labels:
    app: nodeport-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeport-app
  template:
    metadata:
      labels:
        app: nodeport-app
    spec:
      containers:
        - name: nodeport-app
          image: devopseasylearning2021/canary-dev:236c2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: nodeport-app
  annotations:
spec:
  type: NodePort
  selector:
    app: nodeport-app
  ports:
    - port: 80
      targetPort: 80

   