apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc-create-by-efs-csi-driver
  resources: 
    requests:
      storage: 4Gi