apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3-storage-provision-by-ebs-csi-driver
  resources: 
    requests:
      storage: 4Gi