apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-deployment
  labels:
    app: covid19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid19
  template:
    metadata:
      labels:
        app: covid19
    spec:
      containers:
        - name: covid19
          image: leonardtia/tia:microservices
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: covid19-nodeport-service
  labels:
    app: covid19
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /covid19/index.html
spec:
  type: NodePort
  selector:
    app: covid19
  ports:
    - port: 80
      targetPort: 80

   