apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3-storage-class-create-by-terraform
  resources: 
    requests:
      storage: 4Gi